version: '3.8'

networks:
  backend:
    name: bookstore-network

services:
  mssql:
    build: 
      context: ./scripts/sql
    container_name: bookstore-db
    ports:
      - "1433:1433"  
    environment:
      SA_PASSWORD: "P@ssw0rd?"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    networks:
      - backend

  api:
    build:
      context: ./
      dockerfile: ./src/BookStore.WebApi/Dockerfile
    container_name: bookstore-webapi
    depends_on:
      - mssql
    ports:
      - 5001:80
    environment:
      ConnectionStrings__DbConnection: Server=mssql;Database=BookStore;User Id=SA;Password=P@ssw0rd?;Encrypt=False
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - backend